Fixed further errors and warnings
==== Fixed Errors:

- **error: too few arguments to function call, single argument 'context' was not specified**

  Patterns causing the error:
  ```c++
  Nan::FunctionCallbackInfo<v8::Value> &info
  info[0]->ToString()
  ```
  ```c++
  typedef const FunctionCallbackInfo<v8::Value>& NAN_METHOD_ARGS_TYPE;
  #define NAN_METHOD(name)   Nan::NAN_METHOD_RETURN_TYPE name(Nan::NAN_METHOD_ARGS_TYPE info)
  NAN_METHOD(YarpJS_RPCPort::Open) {
    ...
    v8::String::Utf8Value _port_name(info[0]->ToString());
    ...
  }
  ```
  Same use case with `info[0]->IntegerValue()`:
  ```c++
    V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
      Local<Context> context) const;
  ```

  => Add argument `Nan::GetCurrentContext()`.

- **error: no matching function for call to 'Unwrap'**
  (no viable conversion from 'MaybeLocal<v8::Object>' to 'Local<v8::Object>')

  Pattern causing the error:
  ```c++
  YarpJS_Bottle* target = Nan::ObjectWrap::Unwrap<YarpJS_Bottle>(info[0]->ToObject(...));
  ```

  => Replace argument by `info[0]->ToObject(...).ToLocalChecked()`.

- **error: no matching constructor for initialization of 'v8::String::Utf8Value'**
  (no known conversion from 'MaybeLocal<v8::String>' to 'const v8::String::Utf8Value' for 1st argument)

  Prototype of the constructor changed from:
  ```c++
  explicit Utf8Value(Local<v8::Value> obj);
  ```
  to
  ```c++
  Utf8Value(Isolate* isolate, Local<v8::Value> obj);
  ```
  ===== Note: class Isolate
  Isolate represents an isolated instance of the V8 engine. V8 isolates have completely separate states. Objects from one isolate must not be used in other isolates. The embedder can create multiple isolates and use them in parallel in multiple threads. An isolate can be entered by at most one thread at any given time. The Locker/Unlocker API must be used to synchronize.

  Use static method `Isolate::GetCurrent()`.
  ```c++
  namespace v8
  public: static Isolate *Isolate::GetCurrent()
  Returns the entered isolate for the current thread or NULL in case there is no current isolate. This method must not be invoked before V8::Initialize() was invoked.
  ```

- **error: no viable conversion from 'Maybe<int64_t>' (aka 'Maybe<long long>') to 'int'**

  Example:
  ```c++
  int compression_quality = info[0]->IntegerValue(Nan::GetCurrentContext());
  ```
  Since `info[0]->IntegerValue(Nan::GetCurrentContext())` returns `Maybe<int64_t>`, we need to convert the output to `int64_t`, using:
  ```c++
  V8_INLINE T v8::Maybe::FromMaybe(const T& default_value) const {
    return has_value ? value : default_value;
  }
  ```
  (refer to class `Maybe` definition in `v8.h`).

==== Fixed Warnings:

- **warning: 'Mutex' is deprecated: Use std::mutex instead**

- **warning: 'tryLock' is deprecated: Use try_lock() instead**

==== Non fixed warnings:

- **warning: 'Call' is deprecated [-Wdeprecated-declarations]**

  Pattern causing the error:
  ```c++
  tmp_this->callback->Call(tmp_arguments.size(),tmp_arguments.data());
  ```
  --> in `yarp.js/YarpJS/include/YarpJS_Callback.h:124:25`.

- **warning: address of function 'Nan::Null' will always evaluate to 'true'**

  Example:
  ```c++
  v8::Local<v8::Value> argv[1] = {Nan::New(Nan::Null)};
  ```
  --> in `yarp.js/YarpJS/src/YarpJS_BufferedPort_Bottle.cpp:93:44`.
  --> in `yarp.js/YarpJS/src/YarpJS_BufferedPort_Sound.cpp:23:46`.

- **warning: 'getIplImage' is deprecated: Use yarp::cv::toCvMat instead**

  Example:
  ```c++
  internalImage = cv::cvarrToMat((IplImage *) this->getYarpObj()->getIplImage());
  ```
  --> in `yarp.js/YarpJS/src/YarpJS_Image.cpp:23:69`.